### ISSUE TITLE
Potential addition: mTBI 3 Auditory Oddball?

### ISSUE THREAD

**Issue by l-acs** [jessb0t/neuroling-resources#1]
Awesome work:) Not sure what the criteria for inclusion exactly are, but I found [this](http://predict.cs.unm.edu/downloads.php) dataset (#d009) (for [this](https://doi.org/10.1016/j.neuropsychologia.2019.107125) paper) that I'll be using for an EEG analysis course. It involves an auditory oddball task looking at the P3a and P3b components in a clinical population and in healthy controls.

Unfortunately the task does not get at language-specific questions – I chose it because it is notably one of but few open EEG datasets I could find that is stimulus-locked (amenable to ERP or time-frequency analysis) and that also contrasts a neurologically impaired clinical group with controls in a task-based paradigm. So it's not directly language, but it was of interest to me because it _can_ investigate group differences in auditory processing following brain injury.

Hypothetical markdown snippet if you want to add it:

```markdown
### mTBI 3 Auditory Oddball | EEG

An EEG dataset in which 38 participants who had suffered concussions and 24 healthy controls performed a 3 Auditory Oddball task. 

[PRED+CT](http://predict.cs.unm.edu/downloads.php) –– [Paper](https://doi.org/10.1016/j.neuropsychologia.2019.107125)

```

**Comment by jessb0t** [comment]
Thank you, @l-acs ! I added both the mTBI dataset as well as the PD dataset!
